### ISSUE TITLE
Asking for a hint is returning an already used hint/letter

### ISSUE THREAD

**Issue by mauricioabreu** [mauricioabreu/go-hangman#19]
When asking for a hint, the game is choosing an already used letter.

Case:

1. The word is "banana"
2. User asks for a hint
3. They get the letter "b"
4. User asks for a new hint
5. They get the letter "b" again

**Comment by forrcaho** [comment]
I can get this. The way I'm thinking of fixing this is to change the flow so that when AskForHint is called, MakeAGuess will not be. That will also allow me to change the "Good guess!" text which is kind of strange when you've just gotten a hint instead of making a guess.

(edit) ... on further inspection, having MakeAGuess handle the special case of ".h" internally instead of having the flow in the cli code specially handle the hint case would also make the API work without further changes. I think I'll do it that way.
