### ISSUE TITLE
Implement in memory repository

### ISSUE THREAD

**Issue by mauricioabreu** [mauricioabreu/go-hangman#27]
With this feature users don't need to have postgres up and running.

**Comment by forrcaho** [comment]
Ok, I'll give this a shot. Here's my design proposal:

* rename `db/store.go` to `store/pg.go`, changing the dir because this is storage and not necessarily a db, and specifying pg because we should be able to easily add more databases with this change.
* create `store/memory.go` for the in-memory implementation (just a map with the game id as the key, no need for anything more sophisticated AFAICT)
* implement a common interface in `store/common.go` and change all referring code to use the interface. (If you can think of a better name for this file let me know.)
* Choice of which to use will be at instatiation; I'm going to just hard-code this for this step, although later it could go in a config file or something.

Sound good?

**Comment by mauricioabreu** [comment]
Hello @forrcaho 

I think you are absolutely right about the approach.
About fie `common.go` filename, it is ok to me. Good name!

Agreed, you can instantiate either storage backends. Choose one and go ahead. The configuration of the backend can be done via flags but you can leave it out of this issue if you prefer to.

**Comment by mauricioabreu** [comment]
Thank you @forrcaho 
Amazing job
